datatest:
  image: busybox
  volumes:
    - /data

dbtest:
  image: postgres:9.4
  volumes_from:
    - datatest
  ports:
    - "5432:5432"


apitest:
  image: bjan/scrumble-api
  working_dir: /app
  links:
   - dbtest:db
  ports:
    - "8000:8000"
  environment:
    HOST: "0.0.0.0"
    PORT: "8000"
    DB_DATABASE: postgres
    DB_USERNAME: postgres
    GOOGLE_API_SECRET: '***'
    TRELLO_KEY: '***'
    TRELLO_SECRET: '***'
  command: npm test

apptest:
  image: node:wheezy
  volumes:
    - ./client:/app
  working_dir: /app
  ports:
    - "8083:8083"
  environment:
    API_URL: "aa"
    APP_PORT: "8083"
    GOOGLE_CLIENT_ID: aa
    TRELLO_KEY: aa
  command: npm test
